[Refs #346] Named ratio/crop modifiers
inuitcss/inuitcss pull request #352
Opened 2018-02-12 19:10 UTC by herzinger

2018-02-13 22:01 UTC, florianbouvot requested changes
1 - Can we provide a consistent default crop/ratio list ?
Like `3:1`; `2:1`, `16:9`, `4:3` most common video and photo aspect ratio.

2 - Can we harmonize default naming in map ?

Like:
```
$inuit-crops|ratios: (
  "3\\:1" : (3:1),
  "2\\:1" : (2:1),
  "16\\:9" : (16:9),
  "4\\:3" : (4:3),
  "golden-ratio" : (1.618:1) // Not needed by default
) !default;
```

And add description about supported naming `golden-ratio`...?

2018-02-13 22:44 UTC, herzinger commented
I thought about both, and decided against, for one reason: the user shouldn't really use this map anyway. No real project will use the exact same ratios we define here, this is more of a showcase than an actual, useful list. That being the case, the map I defined is a good demo of variated use cases. The different names show some conventions and how to achieve then (and I'd argue the best one should be to give a project specific name, like "hero" or "card"), and the golden ratio shows you can use non-integers. 

To be honest, my preferred solution would be to define it as `null`, like what we decided with the responsive spacings, and have this map as an example in a comment, but I decided to leave it as a discussion for another time, to be something of a framework-wide mentality, maybe in a future version.

2018-02-13 23:42 UTC, herzinger commented
Another point: would we stick with any one convention, it would look like we are endorsing this specific usage. And since the best practice is, in my opinion, to define something project specific, I believe nothing we could write here would constitute good advice, really.

Of course, nothing I said here is out of discussion, and I can change it if the team decide I should.

2018-02-14 14:19 UTC, csshugs approved these changes
> I believe nothing we could write here would constitute good advice, really.

I'm with @herzinger here. I consider it a sensible idea to provide all the possible ways of naming a class and let the user override the default ratios anyway.

2018-02-20 20:44 UTC, dennisfrank commented
@herzinger There is [wrong class in line 131](https://github.com/herzinger/inuitcss/blob/ae258bc0dccacebc8a1b3cfb50030c92fd5e58ad/objects/_objects.crop.scss#L131):

`.o-ratio--#{$crop-name}` instead of `.o-crop--#{$crop-name}`

2018-02-20 22:19 UTC, nenadjelovac commented on objects/_objects.crop.scss
> +    .o-ratio--#{$crop-name} {
As mentioned in https://github.com/inuitcss/inuitcss/pull/352#issuecomment-367112798, this class should be `.o-ratio--#{$crop-name}`

2018-02-20 22:33 UTC, nenadjelovac commented on objects/_objects.crop.scss
> +    .o-ratio--#{$crop-name} {
@dennisfrank thnx for catching this ;) It's getting late in my timezone, the brain is out :D

2018-02-21 03:35 UTC, herzinger commented
@dennisfrank thanks, it should be right now.

Besides that, what is the consensus on the provided default map for this pull request in the end?

2018-02-21 09:42 UTC, csshugs commented
@herzinger As I already stated, I'm fine with it as it showcases the variety of possible ways to name the classes. This is self-documented code par excellence. It's likely that the inuitcss user overrides the map anyway which is easy to do in case.

@florianbouvot Do you have any points against the proposed default maps, that we didn't discussed yet?

2018-02-21 13:37 UTC, nenadjelovac commented
@csshugs @herzinger I'm actually with @florianbouvot on this one. I'd rather we offer sensible defaults (like for [widths fractions](https://github.com/inuitcss/inuitcss/blob/develop/utilities/_utilities.widths.scss#L45) for example), and have this map as an example in a comment.

2018-02-21 15:27 UTC, herzinger commented
I'm okay with that, although as I said, nothing would be REALLY sensible defaults for this. 

That being said, if we follow the `x:y` convention it would also increase backward compatibility. I'll do this, and write some more detailed documentation for now.

2018-02-22 10:48 UTC, csshugs requested changes
This is IMO a very good compromise of providing a sensible default map with a good documented example of other possible class names.

If you could please fix the two typos I annotated, I'd be happy to merge this.

2018-02-22 10:48 UTC, csshugs commented on objects/_objects.crop.scss
> +// the map keys are the strings used in the generated class names, and they can
Sorry for nitpicking, but can you please start the sentence with titlecase.

2018-02-22 10:48 UTC, csshugs commented on objects/_objects.ratio.scss
> +// the map keys are the strings used in the generated class names, and they can
Same as for the crop object: Can you please start the sentence with titlecase.

2018-02-22 12:04 UTC, herzinger commented
Sure, no problem. I agree. 

In exchange, let me nitpick your nitpicking: what you mean is proper case. Title case is Something Like This. Also, you should say "start the sentence with an _uppercase_", or "_write_ the sentence _in_ proper case".

2018-02-22 12:18 UTC, dennisfrank commented
C’mon guys. :wink: 

Most of the contributers aren’t native English speakers. Aiming for a uniform documentation/code language style is fine. But is it really necessary to criticize linguistic subtleties of discussion comments? 

(I’m just a (mostly) silent observer hoping for a v6 release soon with motivated contributors and core team! :smiley:)

2018-02-22 12:39 UTC, herzinger commented
> But is it really necessary to criticize linguistic subtleties of discussion comments?

No, it's not. This was humor. Meta humor. Thats why I added the `xD"` at the end. Like how I only find it funny because I _literally_ am high on acid right now.

And now you are considering in your head if a guy that would do this kind of nitpicking would have used "literally" _figuratively_ in the sentence above. 

Like that.

`xD"`

2018-02-23 07:15 UTC, csshugs approved these changes

2018-02-23 11:21 UTC, florianbouvot approved these changes

2018-02-23 12:21 UTC, merged

2018-02-26 17:30 UTC, Jamiewarb commented
This was an enjoyable read, culminating in a fine solution 👍